<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedOrder extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "kamille.ek_order";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'user_id' => 0,
			'reference' => '',
			'date' => '',
			'tracking_number' => null,
			'user_info' => '',
			'shop_info' => '',
			'invoice_address' => '',
			'billing_address' => '',
			'order_details' => '',
		], $data);


        if (0 === (int)$ret["tracking_number"]) {
            $ret["tracking_number"] = null;
        }

        return $ret;
    }


}