<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedShopHasProduct extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_shop_has_product";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'shop_id' => 0,
			'product_id' => 0,
			'price' => null,
			'wholesale_price' => '',
			'quantity' => 0,
			'active' => 0,
			'_sale_price_without_tax' => '',
			'_sale_price_with_tax' => '',
			'seller_id' => 0,
		], $data);


        if (0 === (int)$ret["price"]) {
            $ret["price"] = null;
        }

        return $ret;
    }


}