<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedUserHasAddress extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_user_has_address";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'user_id' => 0,
			'address_id' => 0,
			'type' => '',
			'order' => 0,
		], $data);



        return $ret;
    }


}