<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedCart extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_cart";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'id' => null,
			'user_id' => 0,
			'date' => '',
			'items' => '',
			'order_date' => null,
			'ip' => '',
			'php_sess_id' => '',
		];
        $ret = array_replace($base, array_intersect_key($data, $base));

        if (0 === (int)$ret["order_date"]) {
            $ret["order_date"] = null;
        }


        return $ret;
    }


}