<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedTaxRuleConditionHasTax extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_tax_rule_condition_has_tax";
        $this->primaryKey = ['tax_rule_condition_id', 'tax_id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'tax_rule_condition_id' => 0,
			'tax_id' => 0,
			'mode' => '',
			'order' => 0,
		];
        $ret = array_replace($base, array_intersect_key($data, $base));



        return $ret;
    }


}