<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedProductCardImage extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_product_card_image";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'id' => null,
			'product_card_id' => 0,
			'url' => '',
			'legend' => '',
			'position' => 0,
			'active' => 0,
			'is_default' => 0,
			'product_id' => null,
			'product_image_is_always_visible' => 0,
		];
        $ret = array_replace($base, array_intersect_key($data, $base));

        if (0 === (int)$ret["product_id"]) {
            $ret["product_id"] = null;
        }


        return $ret;
    }


}