<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedUserHasProductReference extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_user_has_product_reference";
        $this->primaryKey = ['user_id', 'product_reference_id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'user_id' => 0,
			'product_reference_id' => 0,
			'date_added' => '',
			'date_deleted' => '',
		];
        $ret = array_replace($base, array_intersect_key($data, $base));



        return $ret;
    }


}