<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedPasswordRecoveryRequest extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_password_recovery_request";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'id' => null,
			'user_id' => 0,
			'date_created' => '',
			'code' => '',
			'date_used' => null,
		];
        $ret = array_replace($base, array_intersect_key($data, $base));

        if ("" === $ret["date_used"]) {
            $ret["date_used"] = null;
        }


        return $ret;
    }


}