<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedAddress extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "kamille.ek_address";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'type' => '',
			'city' => '',
			'postcode' => '',
			'address' => '',
			'active' => 0,
			'state_id' => null,
			'country_id' => 0,
		], $data);


        if (0 === (int)$ret["state_id"]) {
            $ret["state_id"] = null;
        }

        return $ret;
    }


}