<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedTaxRuleCondition extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_tax_rule_condition";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'id' => null,
			'tax_rule_id' => 0,
			'ratio' => '',
			'cond_user_group_id' => null,
			'cond_extra1' => null,
			'cond_extra2' => null,
			'cond_extra3' => null,
			'cond_extra4' => null,
		];
        $ret = array_replace($base, array_intersect_key($data, $base));

        if (0 === (int)$ret["cond_user_group_id"]) {
            $ret["cond_user_group_id"] = null;
        }
        if (0 === (int)$ret["cond_extra1"]) {
            $ret["cond_extra1"] = null;
        }
        if (0 === (int)$ret["cond_extra2"]) {
            $ret["cond_extra2"] = null;
        }
        if (0 === (int)$ret["cond_extra3"]) {
            $ret["cond_extra3"] = null;
        }
        if (0 === (int)$ret["cond_extra4"]) {
            $ret["cond_extra4"] = null;
        }


        return $ret;
    }


}