<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedOrder extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_order";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'id' => null,
			'user_id' => null,
			'reference' => '',
			'date' => '',
			'amount' => '',
			'cart_total_tax_excluded' => '',
			'shipping_cost_tax_excluded' => '',
			'coupon_saving' => '',
			'cart_quantity' => 0,
			'shipping_country_iso_code' => '',
			'payment_method' => '',
			'payment_method_extra' => '',
			'user_info' => '',
			'store_info' => '',
			'shipping_address' => '',
			'billing_address' => '',
			'order_details' => '',
			'order_origin' => '',
			'currency_iso_code' => '',
		];
        $ret = array_replace($base, array_intersect_key($data, $base));

        if (0 === (int)$ret["user_id"]) {
            $ret["user_id"] = null;
        }


        return $ret;
    }


}