<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedShop extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "kamille.ek_shop";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'label' => '',
			'host' => '',
			'lang_id' => null,
			'currency_id' => null,
			'timezone_id' => null,
		], $data);


        if (0 === (int)$ret["lang_id"]) {
            $ret["lang_id"] = null;
        }
        if (0 === (int)$ret["currency_id"]) {
            $ret["currency_id"] = null;
        }
        if (0 === (int)$ret["timezone_id"]) {
            $ret["timezone_id"] = null;
        }

        return $ret;
    }


}