<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedProductReferenceShopLang extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "kamille.ek_product_reference_shop_lang";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'product_reference_shop_id' => 0,
			'label' => null,
			'description' => null,
		], $data);


        if (0 === (int)$ret["label"]) {
            $ret["label"] = null;
        }
        if (0 === (int)$ret["description"]) {
            $ret["description"] = null;
        }

        return $ret;
    }


}