<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedNewsletter extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_newsletter";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'id' => null,
			'shop_id' => 0,
			'email' => '',
			'subscribe_date' => '',
			'unsubscribe_date' => null,
			'active' => 0,
		];
        $ret = array_replace($base, array_intersect_key($data, $base));

        if (0 === (int)$ret["unsubscribe_date"]) {
            $ret["unsubscribe_date"] = null;
        }


        return $ret;
    }


}