<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedCondition extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "kamille.ek_condition";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'type' => '',
			'combinator' => '',
			'negation' => 0,
			'start_group' => 0,
			'end_group' => 0,
			'left_operand' => '',
			'operator' => '',
			'right_operand' => '',
			'right_operand2' => null,
		], $data);


        if (0 === (int)$ret["right_operand2"]) {
            $ret["right_operand2"] = null;
        }

        return $ret;
    }


}