<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedProductCard extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_product_card";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'id' => null,
			'label' => '',
			'description' => '',
			'slug' => '',
			'meta_title' => '',
			'meta_description' => '',
			'meta_keywords' => '',
			'active' => 0,
			'tax_group_id' => null,
			'product_id' => null,
		];
        $ret = array_replace($base, array_intersect_key($data, $base));

        if (0 === (int)$ret["tax_group_id"]) {
            $ret["tax_group_id"] = null;
        }
        if (0 === (int)$ret["product_id"]) {
            $ret["product_id"] = null;
        }


        return $ret;
    }


}