<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedAddress extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_address";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'id' => null,
			'libelle' => '',
			'phone' => '',
			'address' => '',
			'city' => '',
			'postcode' => '',
			'supplement' => '',
			'active' => 0,
			'country_id' => 0,
			'date_added' => '',
			'date_updated' => '',
		];
        $ret = array_replace($base, array_intersect_key($data, $base));



        return $ret;
    }


}