<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedUser extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_user";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'shop_id' => 0,
			'email' => '',
			'pass' => '',
			'pseudo' => '',
			'first_name' => '',
			'last_name' => '',
			'date_creation' => '',
			'mobile' => '',
			'phone' => '',
			'newsletter' => 0,
			'gender' => 0,
			'birthday' => null,
			'active' => 0,
		];
        $ret = array_replace($base, array_intersect_key($data, $base));

        if (0 === (int)$ret["birthday"]) {
            $ret["birthday"] = null;
        }


        return $ret;
    }


}