<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedUserHasProduct extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_user_has_ek_product";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'ek_user_id' => 0,
			'ek_product_id' => 0,
		], $data);



        return $ret;
    }


}