<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedUser extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_user";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'shop_id' => 0,
			'email' => '',
			'pass' => '',
			'date_creation' => '',
			'mobile' => '',
			'phone' => '',
			'newsletter' => 0,
			'active' => 0,
		], $data);



        return $ret;
    }


}