<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedProduct extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_product";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'id' => null,
			'reference' => '',
			'weight' => '',
			'price' => '',
			'product_card_id' => 0,
			'width' => null,
			'height' => null,
			'depth' => null,
		];
        $ret = array_replace($base, array_intersect_key($data, $base));

        if (0 === (int)$ret["width"]) {
            $ret["width"] = null;
        }
        if (0 === (int)$ret["height"]) {
            $ret["height"] = null;
        }
        if (0 === (int)$ret["depth"]) {
            $ret["depth"] = null;
        }


        return $ret;
    }


}