<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedUserHasCoupon extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_user_has_coupon";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'user_id' => 0,
			'coupon_id' => 0,
			'date' => '',
			'order_id' => null,
		], $data);


        if (0 === (int)$ret["order_id"]) {
            $ret["order_id"] = null;
        }

        return $ret;
    }


}