<?php


namespace Module\Ekom\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedCategory extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "ek_category";
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $ret = array_replace([
			'name' => '',
			'category_id' => null,
			'shop_id' => 0,
		], $data);


        if (0 === (int)$ret["category_id"]) {
            $ret["category_id"] = null;
        }

        return $ret;
    }


}