-- MySQL Script generated by MySQL Workbench
-- Fri Feb  9 16:10:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kamille
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kamille
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kamille` DEFAULT CHARACTER SET utf8 ;
USE `kamille` ;

-- -----------------------------------------------------
-- Table `kamille`.`ek_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_lang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `iso_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iso_code_UNIQUE` (`iso_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_backoffice_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_backoffice_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `shop_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_currency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iso_code` VARCHAR(3) NOT NULL,
  `symbol` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iso_code_UNIQUE` (`iso_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_timezone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_timezone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NOT NULL,
  `host` VARCHAR(128) NOT NULL,
  `lang_id` INT NULL,
  `currency_id` INT NULL,
  `base_currency_id` INT NULL,
  `timezone_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shop_lang1_idx` (`lang_id` ASC),
  INDEX `fk_shop_currency1_idx` (`currency_id` ASC),
  INDEX `fk_shop_timezone1_idx` (`timezone_id` ASC),
  UNIQUE INDEX `host_UNIQUE` (`host` ASC),
  INDEX `fk_ek_shop_ek_currency1_idx` (`base_currency_id` ASC),
  CONSTRAINT `fk_shop_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_currency1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `kamille`.`ek_currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_timezone1`
    FOREIGN KEY (`timezone_id`)
    REFERENCES `kamille`.`ek_timezone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ek_shop_ek_currency1`
    FOREIGN KEY (`base_currency_id`)
    REFERENCES `kamille`.`ek_currency` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_configuration` (
  `shop_id` INT NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `value` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`shop_id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  CONSTRAINT `fk_shop_configuration_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_lang` (
  `shop_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`, `lang_id`),
  INDEX `fk_shop_has_lang_lang1_idx` (`lang_id` ASC),
  INDEX `fk_shop_has_lang_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_shop_has_lang_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shop_has_lang_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_currency` (
  `shop_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  `exchange_rate` DECIMAL(20,6) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`shop_id`, `currency_id`),
  INDEX `fk_shop_has_currency_currency1_idx` (`currency_id` ASC),
  INDEX `fk_shop_has_currency_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_shop_has_currency_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shop_has_currency_currency1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `kamille`.`ek_currency` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_card` (
  `id` INT GENERATED ALWAYS AS (),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(64) NOT NULL,
  `weight` DECIMAL(20,6) NOT NULL,
  `price` DECIMAL(20,2) NOT NULL,
  `product_card_id` INT NOT NULL,
  `width` DECIMAL(20,6) NULL,
  `height` DECIMAL(20,6) NULL,
  `depth` DECIMAL(20,6) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reference_UNIQUE` (`reference` ASC),
  INDEX `fk_ek_product_ek_product_card1_idx` (`product_card_id` ASC),
  CONSTRAINT `fk_ek_product_ek_product_card1`
    FOREIGN KEY (`product_card_id`)
    REFERENCES `kamille`.`ek_product_card` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_seller` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_seller_ek_shop1_idx` (`shop_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC, `shop_id` ASC),
  CONSTRAINT `fk_ek_seller_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC, `shop_id` ASC),
  INDEX `fk_ek_product_type_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ek_product_type_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_manufacturer_ek_shop1_idx` (`shop_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC, `shop_id` ASC),
  CONSTRAINT `fk_ek_manufacturer_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_product` (
  `shop_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `price` DECIMAL(20,2) NULL,
  `wholesale_price` DECIMAL(20,2) NOT NULL,
  `quantity` INT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `_discount_badge` VARCHAR(256) NOT NULL,
  `seller_id` INT NOT NULL,
  `product_type_id` INT NOT NULL,
  `reference` VARCHAR(64) NOT NULL,
  `_popularity` DECIMAL(20,2) NOT NULL,
  `codes` TEXT NOT NULL,
  `manufacturer_id` INT NULL,
  `ean` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`shop_id`, `product_id`),
  INDEX `fk_shop_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_shop_has_product_shop1_idx` (`shop_id` ASC),
  INDEX `fk_ek_shop_has_product_ek_seller1_idx` (`seller_id` ASC),
  INDEX `fk_ek_shop_has_product_ek_product_type1_idx` (`product_type_id` ASC),
  INDEX `fk_ek_shop_has_product_ek_manufacturer1_idx` (`manufacturer_id` ASC),
  CONSTRAINT `fk_shop_has_product_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shop_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `kamille`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_product_ek_seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `kamille`.`ek_seller` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_product_ek_product_type1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `kamille`.`ek_product_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_product_ek_manufacturer1`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `kamille`.`ek_manufacturer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_attribute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_attribute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_attribute_value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_has_product_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_has_product_attribute` (
  `product_id` INT NOT NULL,
  `product_attribute_id` INT NOT NULL,
  `product_attribute_value_id` INT NOT NULL,
  `order` TINYINT(1) NOT NULL,
  PRIMARY KEY (`product_id`, `product_attribute_id`, `product_attribute_value_id`),
  INDEX `fk_product_has_product_attribute_product_attribute1_idx` (`product_attribute_id` ASC),
  INDEX `fk_product_has_product_attribute_product1_idx` (`product_id` ASC),
  INDEX `fk_product_has_product_attribute_product_attribute_value1_idx` (`product_attribute_value_id` ASC),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC, `product_attribute_id` ASC),
  CONSTRAINT `fk_product_has_product_attribute_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `kamille`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_has_product_attribute_product_attribute1`
    FOREIGN KEY (`product_attribute_id`)
    REFERENCES `kamille`.`ek_product_attribute` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_has_product_attribute_product_attribute_value1`
    FOREIGN KEY (`product_attribute_value_id`)
    REFERENCES `kamille`.`ek_product_attribute_value` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_attribute_value_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_attribute_value_lang` (
  `product_attribute_value_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `value` VARCHAR(64) NOT NULL,
  INDEX `fk_ek_product_attribute_value_lang_ek_product_attribute_val_idx` (`product_attribute_value_id` ASC),
  INDEX `fk_ek_product_attribute_value_lang_ek_lang1_idx` (`lang_id` ASC),
  PRIMARY KEY (`product_attribute_value_id`, `lang_id`),
  CONSTRAINT `fk_ek_product_attribute_value_lang_ek_product_attribute_value1`
    FOREIGN KEY (`product_attribute_value_id`)
    REFERENCES `kamille`.`ek_product_attribute_value` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_attribute_value_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_attribute_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_attribute_lang` (
  `product_attribute_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  INDEX `fk_ek_product_attribute_lang_ek_product_attribute1_idx` (`product_attribute_id` ASC),
  INDEX `fk_ek_product_attribute_lang_ek_lang1_idx` (`lang_id` ASC),
  PRIMARY KEY (`product_attribute_id`, `lang_id`),
  CONSTRAINT `fk_ek_product_attribute_lang_ek_product_attribute1`
    FOREIGN KEY (`product_attribute_id`)
    REFERENCES `kamille`.`ek_product_attribute` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_attribute_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_card_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_card_lang` (
  `product_card_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `label` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `meta_title` VARCHAR(128) NOT NULL,
  `meta_description` VARCHAR(256) NOT NULL,
  `meta_keywords` TEXT NOT NULL,
  INDEX `fk_ek_product_lang_ek_product_card1_idx` (`product_card_id` ASC),
  INDEX `fk_ek_product_lang_ek_lang2_idx` (`lang_id` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC, `lang_id` ASC),
  PRIMARY KEY (`product_card_id`, `lang_id`),
  CONSTRAINT `fk_ek_product_lang_ek_product_card1`
    FOREIGN KEY (`product_card_id`)
    REFERENCES `kamille`.`ek_product_card` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_lang_ek_lang2`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_lang` (
  `product_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `label` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  `meta_title` VARCHAR(128) NOT NULL,
  `meta_description` VARCHAR(256) NOT NULL,
  `meta_keywords` TEXT NOT NULL,
  INDEX `fk_ek_product_lang_ek_product1_idx` (`product_id` ASC),
  INDEX `fk_ek_product_lang_ek_lang1_idx` (`lang_id` ASC),
  PRIMARY KEY (`product_id`, `lang_id`),
  CONSTRAINT `fk_ek_product_lang_ek_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `kamille`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_product_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_product_lang` (
  `shop_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `label` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `out_of_stock_text` VARCHAR(128) NOT NULL,
  `meta_title` VARCHAR(128) NOT NULL,
  `meta_description` VARCHAR(256) NOT NULL,
  `meta_keywords` TEXT NOT NULL,
  INDEX `fk_ek_shop_has_product_lang_ek_shop_has_product1_idx` (`shop_id` ASC, `product_id` ASC),
  INDEX `fk_ek_shop_has_product_lang_ek_lang1_idx` (`lang_id` ASC),
  PRIMARY KEY (`lang_id`, `product_id`, `shop_id`),
  CONSTRAINT `fk_ek_shop_has_product_lang_ek_shop_has_product1`
    FOREIGN KEY (`shop_id` , `product_id`)
    REFERENCES `kamille`.`ek_shop_has_product` (`shop_id` , `product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_product_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `category_id` INT NULL,
  `shop_id` INT NOT NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC, `shop_id` ASC),
  INDEX `fk_category_category1_idx` (`category_id` ASC),
  INDEX `fk_ek_category_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `kamille`.`ek_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_category_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_category_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_category_lang` (
  `category_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `label` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `meta_title` VARCHAR(128) NOT NULL,
  `meta_description` VARCHAR(256) NOT NULL,
  `meta_keywords` TEXT NOT NULL,
  INDEX `fk_category_lang_category1_idx` (`category_id` ASC),
  INDEX `fk_category_lang_ek_lang1_idx` (`lang_id` ASC),
  PRIMARY KEY (`lang_id`, `category_id`),
  UNIQUE INDEX `slug_UNIQUE` (`category_id` ASC, `lang_id` ASC, `slug` ASC),
  CONSTRAINT `fk_category_lang_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `kamille`.`ek_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_category_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_category_has_product_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_category_has_product_card` (
  `category_id` INT NOT NULL,
  `product_card_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `product_card_id`),
  INDEX `fk_ek_category_has_ek_product_card_ek_product_card1_idx` (`product_card_id` ASC),
  INDEX `fk_ek_category_has_ek_product_card_ek_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_ek_category_has_ek_product_card_ek_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `kamille`.`ek_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_category_has_ek_product_card_ek_product_card1`
    FOREIGN KEY (`product_card_id`)
    REFERENCES `kamille`.`ek_product_card` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_tax_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_tax_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `label` VARCHAR(128) NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_tax_group_ek_shop1_idx` (`shop_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC, `shop_id` ASC),
  CONSTRAINT `fk_ek_tax_group_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_product_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_product_card` (
  `shop_id` INT NOT NULL,
  `product_card_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `tax_group_id` INT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`shop_id`, `product_card_id`),
  INDEX `fk_ek_shop_has_ek_product_card_ek_product_card1_idx` (`product_card_id` ASC),
  INDEX `fk_ek_shop_has_ek_product_card_ek_shop1_idx` (`shop_id` ASC),
  INDEX `fk_ek_shop_has_product_card_ek_product1_idx` (`product_id` ASC),
  INDEX `fk_ek_shop_has_product_card_ek_tax_group1_idx` (`tax_group_id` ASC),
  CONSTRAINT `fk_ek_shop_has_ek_product_card_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_ek_product_card_ek_product_card1`
    FOREIGN KEY (`product_card_id`)
    REFERENCES `kamille`.`ek_product_card` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_product_card_ek_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `kamille`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_product_card_ek_tax_group1`
    FOREIGN KEY (`tax_group_id`)
    REFERENCES `kamille`.`ek_tax_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_product_card_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_product_card_lang` (
  `shop_id` INT NOT NULL,
  `product_card_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `label` VARCHAR(128) NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  `meta_title` VARCHAR(128) NOT NULL,
  `meta_description` VARCHAR(256) NOT NULL,
  `meta_keywords` TEXT NOT NULL,
  INDEX `fk_ek_shop_has_product_card_lang_ek_shop_has_product_card1_idx` (`shop_id` ASC, `product_card_id` ASC),
  INDEX `fk_ek_shop_has_product_card_lang_ek_lang1_idx` (`lang_id` ASC),
  PRIMARY KEY (`shop_id`, `product_card_id`, `lang_id`),
  CONSTRAINT `fk_ek_shop_has_product_card_lang_ek_shop_has_product_card1`
    FOREIGN KEY (`shop_id` , `product_card_id`)
    REFERENCES `kamille`.`ek_shop_has_product_card` (`shop_id` , `product_card_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_product_card_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_tax` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_tax_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_tax_lang` (
  `tax_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `label` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`tax_id`, `lang_id`),
  INDEX `fk_tax_has_ek_lang_ek_lang1_idx` (`lang_id` ASC),
  INDEX `fk_tax_has_ek_lang_tax1_idx` (`tax_id` ASC),
  CONSTRAINT `fk_tax_has_ek_lang_tax1`
    FOREIGN KEY (`tax_id`)
    REFERENCES `kamille`.`ek_tax` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tax_has_ek_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_tax_group_has_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_tax_group_has_tax` (
  `tax_group_id` INT NOT NULL,
  `tax_id` INT NOT NULL,
  `order` TINYINT NOT NULL,
  `mode` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`tax_group_id`, `tax_id`),
  INDEX `fk_tax_group_has_tax_tax1_idx` (`tax_id` ASC),
  INDEX `fk_tax_group_has_tax_tax_group1_idx` (`tax_group_id` ASC),
  CONSTRAINT `fk_tax_group_has_tax_tax_group1`
    FOREIGN KEY (`tax_group_id`)
    REFERENCES `kamille`.`ek_tax_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tax_group_has_tax_tax1`
    FOREIGN KEY (`tax_id`)
    REFERENCES `kamille`.`ek_tax` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `pseudo` VARCHAR(64) NOT NULL,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `mobile` VARCHAR(24) NOT NULL,
  `phone` VARCHAR(24) NOT NULL,
  `phone_prefix` VARCHAR(12) NOT NULL,
  `newsletter` TINYINT(1) NOT NULL,
  `gender` TINYINT(1) NOT NULL,
  `birthday` DATE NULL,
  `active_hash` VARCHAR(64) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_ek_shop1_idx` (`shop_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC, `shop_id` ASC),
  UNIQUE INDEX `active_hash_UNIQUE` (`active_hash` ASC),
  CONSTRAINT `fk_user_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_discount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(64) NOT NULL,
  `operand` VARCHAR(64) NOT NULL,
  `target` VARCHAR(64) NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discount_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_discount_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_user_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_ek_user_group_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ek_user_group_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_user_has_user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_user_has_user_group` (
  `user_id` INT NOT NULL,
  `user_group_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_group_id`),
  INDEX `fk_ek_user_has_ek_user_group_ek_user_group1_idx` (`user_group_id` ASC),
  INDEX `fk_ek_user_has_ek_user_group_ek_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ek_user_has_ek_user_group_ek_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kamille`.`ek_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_user_has_ek_user_group_ek_user_group1`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `kamille`.`ek_user_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_discount_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_discount_lang` (
  `discount_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `label` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`discount_id`, `lang_id`),
  INDEX `fk_ek_discount_has_ek_lang_ek_lang1_idx` (`lang_id` ASC),
  INDEX `fk_ek_discount_has_ek_lang_ek_discount1_idx` (`discount_id` ASC),
  CONSTRAINT `fk_ek_discount_has_ek_lang_ek_discount1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `kamille`.`ek_discount` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_discount_has_ek_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_has_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_has_discount` (
  `product_id` INT NOT NULL,
  `discount_id` INT NOT NULL,
  `conditions` TEXT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`product_id`, `discount_id`),
  INDEX `fk_ek_product_has_ek_discount_ek_discount1_idx` (`discount_id` ASC),
  INDEX `fk_ek_product_has_ek_discount_ek_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_ek_product_has_ek_discount_ek_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `kamille`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_has_ek_discount_ek_discount1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `kamille`.`ek_discount` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_card_has_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_card_has_discount` (
  `product_card_id` INT NOT NULL,
  `discount_id` INT NOT NULL,
  `conditions` TEXT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`product_card_id`, `discount_id`),
  INDEX `fk_ek_product_card_has_ek_discount_ek_discount1_idx` (`discount_id` ASC),
  INDEX `fk_ek_product_card_has_ek_discount_ek_product_card1_idx` (`product_card_id` ASC),
  CONSTRAINT `fk_ek_product_card_has_ek_discount_ek_product_card1`
    FOREIGN KEY (`product_card_id`)
    REFERENCES `kamille`.`ek_product_card` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_card_has_ek_discount_ek_discount1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `kamille`.`ek_discount` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_category_has_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_category_has_discount` (
  `category_id` INT NOT NULL,
  `discount_id` INT NOT NULL,
  `conditions` TEXT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`category_id`, `discount_id`),
  INDEX `fk_ek_category_has_ek_discount_ek_discount1_idx` (`discount_id` ASC),
  INDEX `fk_ek_category_has_ek_discount_ek_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_ek_category_has_ek_discount_ek_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `kamille`.`ek_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_category_has_ek_discount_ek_discount1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `kamille`.`ek_discount` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NULL,
  `user_id` INT NULL,
  `reference` VARCHAR(64) NOT NULL,
  `date` DATETIME NOT NULL,
  `amount` DECIMAL(20,2) NOT NULL,
  `coupon_saving` DECIMAL(20,2) NOT NULL,
  `cart_quantity` INT NOT NULL,
  `currency_iso_code` VARCHAR(3) NOT NULL,
  `lang_iso_code` VARCHAR(3) NOT NULL,
  `payment_method` VARCHAR(64) NOT NULL,
  `payment_method_extra` VARCHAR(64) NOT NULL,
  `user_info` BLOB NOT NULL,
  `shop_info` BLOB NOT NULL,
  `shipping_address` BLOB NOT NULL,
  `billing_address` BLOB NOT NULL,
  `order_details` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_order_ek_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `reference_UNIQUE` (`reference` ASC),
  INDEX `fk_ek_order_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ek_order_ek_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kamille`.`ek_user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_order_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_order_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `color` VARCHAR(32) NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_order_status_ek_shop1_idx` (`shop_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC, `shop_id` ASC),
  CONSTRAINT `fk_ek_order_status_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_order_status_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_order_status_lang` (
  `order_status_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `label` VARCHAR(64) NOT NULL,
  INDEX `fk_ek_order_status_lang_ek_order_status1_idx` (`order_status_id` ASC),
  INDEX `fk_ek_order_status_lang_ek_lang1_idx` (`lang_id` ASC),
  PRIMARY KEY (`order_status_id`, `lang_id`),
  CONSTRAINT `fk_ek_order_status_lang_ek_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `kamille`.`ek_order_status` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_order_status_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_order_has_order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_order_has_order_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `order_status_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `extra` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_order_has_ek_order_status_ek_order_status1_idx` (`order_status_id` ASC),
  INDEX `fk_ek_order_has_ek_order_status_ek_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_ek_order_has_ek_order_status_ek_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `kamille`.`ek_order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_order_has_ek_order_status_ek_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `kamille`.`ek_order_status` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_coupon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `procedure_type` VARCHAR(64) NOT NULL,
  `procedure_operand` VARCHAR(128) NOT NULL,
  `target` VARCHAR(256) NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_coupon_ek_shop1_idx` (`shop_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC, `shop_id` ASC),
  CONSTRAINT `fk_ek_coupon_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_coupon_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_coupon_lang` (
  `coupon_id` INT NOT NULL,
  `lang_id` INT NOT NULL COMMENT '	',
  `label` VARCHAR(256) NOT NULL,
  INDEX `fk_ek_coupon_lang_ek_coupon1_idx` (`coupon_id` ASC),
  PRIMARY KEY (`lang_id`, `coupon_id`),
  CONSTRAINT `fk_ek_coupon_lang_ek_coupon1`
    FOREIGN KEY (`coupon_id`)
    REFERENCES `kamille`.`ek_coupon` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_coupon_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iso_code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iso_code_UNIQUE` (`iso_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `phone` VARCHAR(64) NOT NULL,
  `phone_prefix` VARCHAR(12) NOT NULL,
  `address` VARCHAR(256) NOT NULL,
  `city` VARCHAR(128) NOT NULL,
  `postcode` VARCHAR(64) NOT NULL,
  `supplement` VARCHAR(128) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_address_ek_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_ek_address_ek_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `kamille`.`ek_country` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_country_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_country_lang` (
  `country_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `label` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`country_id`, `lang_id`),
  INDEX `fk_ek_country_has_ek_lang_ek_lang1_idx` (`lang_id` ASC),
  INDEX `fk_ek_country_has_ek_lang_ek_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_ek_country_has_ek_lang_ek_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `kamille`.`ek_country` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_country_has_ek_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_user_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_user_has_address` (
  `user_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `order` TINYINT(1) NOT NULL,
  `is_default_shipping_address` TINYINT(1) NOT NULL,
  `is_default_billing_address` TINYINT(1) NOT NULL,
  INDEX `fk_ek_user_has_ek_address_ek_address1_idx` (`address_id` ASC),
  INDEX `fk_ek_user_has_ek_address_ek_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`user_id`, `address_id`),
  CONSTRAINT `fk_ek_user_has_ek_address_ek_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kamille`.`ek_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_user_has_ek_address_ek_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `kamille`.`ek_address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_carrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_carrier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_carrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_carrier` (
  `shop_id` INT NOT NULL,
  `carrier_id` INT NOT NULL,
  `priority` TINYINT(1) NOT NULL,
  PRIMARY KEY (`shop_id`, `carrier_id`),
  INDEX `fk_ek_shop_has_ek_carrier_ek_carrier1_idx` (`carrier_id` ASC),
  INDEX `fk_ek_shop_has_ek_carrier_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ek_shop_has_ek_carrier_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_ek_carrier_ek_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `kamille`.`ek_carrier` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_shop_has_ek_address_ek_address1_idx` (`address_id` ASC),
  INDEX `fk_ek_shop_has_ek_address_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ek_shop_has_ek_address_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_ek_address_ek_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `kamille`.`ek_address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_payment_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_payment_method` (
  `shop_id` INT NOT NULL,
  `payment_method_id` INT NOT NULL,
  `order` INT NOT NULL,
  `configuration` TEXT NOT NULL,
  PRIMARY KEY (`shop_id`, `payment_method_id`),
  INDEX `fk_ek_shop_has_payment_method_payment_method1_idx` (`payment_method_id` ASC),
  INDEX `fk_ek_shop_has_payment_method_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ek_shop_has_payment_method_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_payment_method_payment_method1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `kamille`.`ek_payment_method` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_user_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_user_has_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `product_details` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `deleted_date` DATETIME NULL,
  INDEX `fk_ek_user_has_ek_product_ek_product1_idx` (`product_id` ASC),
  INDEX `fk_ek_user_has_ek_product_ek_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ek_user_has_ek_product_ek_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kamille`.`ek_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_user_has_ek_product_ek_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `kamille`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `rating` TINYINT NOT NULL,
  `useful_counter` INT NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `comment` TEXT NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_product_comment_ek_product1_idx` (`product_id` ASC),
  INDEX `fk_ek_product_comment_ek_user1_idx` (`user_id` ASC),
  INDEX `fk_ek_product_comment_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ek_product_comment_ek_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `kamille`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_comment_ek_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kamille`.`ek_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_comment_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_feature` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_feature_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_feature_value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feature_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_feature_value_ek_feature1_idx` (`feature_id` ASC),
  CONSTRAINT `fk_ek_feature_value_ek_feature1`
    FOREIGN KEY (`feature_id`)
    REFERENCES `kamille`.`ek_feature` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_feature_value_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_feature_value_lang` (
  `feature_value_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `value` TEXT NOT NULL,
  INDEX `fk_ek_feature_value_lang_ek_feature_value1_idx` (`feature_value_id` ASC),
  INDEX `fk_ek_feature_value_lang_ek_lang1_idx` (`lang_id` ASC),
  PRIMARY KEY (`feature_value_id`, `lang_id`),
  CONSTRAINT `fk_ek_feature_value_lang_ek_feature_value1`
    FOREIGN KEY (`feature_value_id`)
    REFERENCES `kamille`.`ek_feature_value` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_feature_value_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_feature_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_feature_lang` (
  `feature_id` INT NOT NULL,
  `lang_id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  INDEX `fk_ek_feature_lang_ek_feature1_idx` (`feature_id` ASC),
  INDEX `fk_ek_feature_lang_ek_lang1_idx` (`lang_id` ASC),
  PRIMARY KEY (`lang_id`, `feature_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC, `lang_id` ASC),
  CONSTRAINT `fk_ek_feature_lang_ek_feature1`
    FOREIGN KEY (`feature_id`)
    REFERENCES `kamille`.`ek_feature` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_feature_lang_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_has_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_has_feature` (
  `product_id` INT NOT NULL,
  `feature_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `feature_value_id` INT NOT NULL,
  `position` TINYINT(1) NOT NULL,
  `technical_description` TEXT NOT NULL,
  PRIMARY KEY (`product_id`, `feature_id`, `shop_id`),
  INDEX `fk_ek_product_has_ek_feature_ek_feature1_idx` (`feature_id` ASC),
  INDEX `fk_ek_product_has_ek_feature_ek_product1_idx` (`product_id` ASC),
  INDEX `fk_ek_product_has_feature_ek_shop1_idx` (`shop_id` ASC),
  INDEX `fk_ek_product_has_feature_ek_feature_value1_idx` (`feature_value_id` ASC),
  CONSTRAINT `fk_ek_product_has_ek_feature_ek_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `kamille`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_has_ek_feature_ek_feature1`
    FOREIGN KEY (`feature_id`)
    REFERENCES `kamille`.`ek_feature` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_has_feature_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_has_feature_ek_feature_value1`
    FOREIGN KEY (`feature_value_id`)
    REFERENCES `kamille`.`ek_feature_value` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_bundle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_bundle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_product_bundle_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ek_product_bundle_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_bundle_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_bundle_has_product` (
  `product_bundle_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`product_bundle_id`, `product_id`),
  INDEX `fk_ek_product_bundle_has_ek_product_ek_product1_idx` (`product_id` ASC),
  INDEX `fk_ek_product_bundle_has_ek_product_ek_product_bundle1_idx` (`product_bundle_id` ASC),
  CONSTRAINT `fk_ek_product_bundle_has_ek_product_ek_product_bundle1`
    FOREIGN KEY (`product_bundle_id`)
    REFERENCES `kamille`.`ek_product_bundle` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_bundle_has_ek_product_ek_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `kamille`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_card` (
  `id` INT GENERATED ALWAYS AS (),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_password_recovery_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_password_recovery_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `date_created` DATETIME NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `date_used` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_password_recovery_request_ek_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ek_password_recovery_request_ek_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kamille`.`ek_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC, `shop_id` ASC),
  INDEX `fk_ek_product_group_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ek_product_group_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_group_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_group_has_product` (
  `product_group_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`product_group_id`, `product_id`),
  INDEX `fk_ek_product_group_has_ek_product_ek_product1_idx` (`product_id` ASC),
  INDEX `fk_ek_product_group_has_ek_product_ek_product_group1_idx` (`product_group_id` ASC),
  CONSTRAINT `fk_ek_product_group_has_ek_product_ek_product_group1`
    FOREIGN KEY (`product_group_id`)
    REFERENCES `kamille`.`ek_product_group` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_product_group_has_ek_product_ek_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `kamille`.`ek_product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NULL,
  `user_id` INT NULL,
  `order_id` INT NOT NULL,
  `seller_id` INT NULL,
  `label` VARCHAR(256) NOT NULL,
  `invoice_number` VARCHAR(64) NOT NULL,
  `invoice_number_alt` VARCHAR(64) NULL,
  `invoice_date` DATETIME NOT NULL,
  `payment_method` VARCHAR(64) NOT NULL,
  `currency_iso_code` VARCHAR(3) NOT NULL,
  `lang_iso_code` VARCHAR(3) NOT NULL,
  `shop_host` VARCHAR(128) NOT NULL,
  `track_identifier` VARCHAR(512) NOT NULL,
  `amount` DECIMAL(20,2) NOT NULL,
  `seller` VARCHAR(64) NOT NULL,
  `user_info` BLOB NOT NULL,
  `seller_address` BLOB NOT NULL,
  `shipping_address` BLOB NOT NULL,
  `billing_address` BLOB NOT NULL,
  `invoice_details` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `invoice_number_UNIQUE` (`invoice_number` ASC),
  UNIQUE INDEX `invoice_number_alt_UNIQUE` (`invoice_number_alt` ASC),
  INDEX `fk_ek_invoice_ek_order1_idx` (`order_id` ASC),
  INDEX `fk_ek_invoice_ek_user1_idx` (`user_id` ASC),
  INDEX `fk_ek_invoice_ek_seller1_idx` (`seller_id` ASC),
  INDEX `fk_ek_invoice_ek_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_ek_invoice_ek_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `kamille`.`ek_order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_invoice_ek_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kamille`.`ek_user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_invoice_ek_seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `kamille`.`ek_seller` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_invoice_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_seller_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_seller_has_address` (
  `seller_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`seller_id`, `address_id`),
  INDEX `fk_ek_seller_has_ek_address_ek_address1_idx` (`address_id` ASC),
  INDEX `fk_ek_seller_has_ek_address_ek_seller1_idx` (`seller_id` ASC),
  CONSTRAINT `fk_ek_seller_has_ek_address_ek_seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `kamille`.`ek_seller` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_seller_has_ek_address_ek_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `kamille`.`ek_address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_direct_debit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_direct_debit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `invoice_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `paid` TINYINT(1) NOT NULL,
  `feedback_details` TEXT NOT NULL,
  `amount` DECIMAL(20,6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_payment_ek_invoice1_idx` (`invoice_id` ASC),
  CONSTRAINT `fk_ek_payment_ek_invoice1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `kamille`.`ek_invoice` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_newsletter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `subscribe_date` DATETIME NOT NULL,
  `unsubscribe_date` DATETIME NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_product_purchase_stat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_product_purchase_stat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchase_date` DATETIME NOT NULL,
  `shop_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `product_ref` VARCHAR(64) NOT NULL,
  `product_label` VARCHAR(64) NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(20,2) NOT NULL,
  `price_without_tax` DECIMAL(20,2) NOT NULL,
  `total` DECIMAL(20,2) NOT NULL,
  `total_without_tax` DECIMAL(20,2) NOT NULL,
  `attribute_selection` BLOB NOT NULL,
  `product_details_selection` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_provider` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek-provider_ek_shop1_idx` (`shop_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC, `shop_id` ASC),
  CONSTRAINT `fk_ek-provider_ek_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `kamille`.`ek_shop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `lang_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ek_tag_ek_lang1_idx` (`lang_id` ASC),
  CONSTRAINT `fk_ek_tag_ek_lang1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `kamille`.`ek_lang` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_product_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_product_has_tag` (
  `shop_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`, `product_id`, `tag_id`),
  INDEX `fk_ek_shop_has_product_has_ek_tag_ek_tag1_idx` (`tag_id` ASC),
  INDEX `fk_ek_shop_has_product_has_ek_tag_ek_shop_has_product1_idx` (`shop_id` ASC, `product_id` ASC),
  CONSTRAINT `fk_ek_shop_has_product_has_ek_tag_ek_shop_has_product1`
    FOREIGN KEY (`shop_id` , `product_id`)
    REFERENCES `kamille`.`ek_shop_has_product` (`shop_id` , `product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_product_has_ek_tag_ek_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `kamille`.`ek_tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`ek_shop_has_product_has_provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`ek_shop_has_product_has_provider` (
  `shop_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  `wholesale_price` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`shop_id`, `product_id`, `provider_id`),
  INDEX `fk_ek_shop_has_product_has_ek_provider_ek_provider1_idx` (`provider_id` ASC),
  INDEX `fk_ek_shop_has_product_has_ek_provider_ek_shop_has_product1_idx` (`shop_id` ASC, `product_id` ASC),
  CONSTRAINT `fk_ek_shop_has_product_has_ek_provider_ek_shop_has_product1`
    FOREIGN KEY (`shop_id` , `product_id`)
    REFERENCES `kamille`.`ek_shop_has_product` (`shop_id` , `product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ek_shop_has_product_has_ek_provider_ek_provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `kamille`.`ek_provider` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
