<?php


namespace Module\Ekom\HybridList\HybridListControl;

use HybridList\HybridListInterface;


/**
 * LingTalfi presents:
 * ++++++++++++++++++++++++++++++++
 *      HYBRID LIST CONTROL
 * ++++++++++++++++++++++++++++++++
 * Featuring the HybridList technology (sorry, couldn't resist).
 *
 *
 *
 *
 * Hybrid list control
 * =====================
 * On a product list, an hybrid list control is an object responsible for:
 *
 * - creating the model for the hybrid control widget (through which the user interacts with the list)
 * - shape the list of items (either shaping the sql request or even the php rows directly) so that
 *      the generated list reacts to the parameters generated by the widget
 *
 *
 *
 */
interface HybridListControlInterface
{

    /**
     *
     * This method is used to shape the list of items.
     * It can also be used to prepare some part of the model, in conjunction with the more
     * dedicated getModel method, or all of it.
     *
     *
     * @param HybridListInterface $list
     * @param array $context, given by the caller: useful variables
     * @return HybridListControlInterface
     */
    public function prepareHybridList(HybridListInterface $list, array $context);

    /**
     * @return array, the model for the HybridListControl widget.
     *      prepareHybridList method must be called first.
     *
     */
    public function getModel();

}