<?php


namespace Module\Ekom\Api;

use Module\Ekom\Api\Object\BackofficeUser;
use Module\Ekom\Api\Object\Currency;
use Module\Ekom\Api\Object\Lang;
use Module\Ekom\Api\Object\Product;
use Module\Ekom\Api\Object\ProductAttribute;
use Module\Ekom\Api\Object\ProductAttributeLang;
use Module\Ekom\Api\Object\ProductAttributeValue;
use Module\Ekom\Api\Object\ProductAttributeValueLang;
use Module\Ekom\Api\Object\ProductCard;
use Module\Ekom\Api\Object\ProductCardHasProduct;
use Module\Ekom\Api\Object\ProductCardLang;
use Module\Ekom\Api\Object\ProductHasProductAttribute;
use Module\Ekom\Api\Object\ProductLang;
use Module\Ekom\Api\Object\Shop;
use Module\Ekom\Api\Object\ShopConfiguration;
use Module\Ekom\Api\Object\ShopHasCurrency;
use Module\Ekom\Api\Object\ShopHasProductCard;
use Module\Ekom\Api\Object\ShopHasLang;
use Module\Ekom\Api\Object\ShopHasProduct;
use Module\Ekom\Api\Object\ShopHasProductLang;
use Module\Ekom\Api\Object\ShopHasStore;
use Module\Ekom\Api\Object\Store;
use Module\Ekom\Api\Object\StoreHasProduct;
use Module\Ekom\Api\Object\Timezone;

use XiaoApi\Api\XiaoApi;


/**
 * IMPORTANT NOTE:
 * -------------------
 * This class is generated by a script, don't edit it manually, or you might loose
 * you changes on the next update.
 *
 *
 * The goal of this class is to generate explicit method names, so that you can benefit
 * your IDE's auto-completion features.
 */
class GeneratedEkomApi extends XiaoApi
{
        /**
     * @return BackofficeUser
     */
    public function backofficeUser()
    {
        return $this->getObject('backofficeUser');
    }    /**
     * @return Currency
     */
    public function currency()
    {
        return $this->getObject('currency');
    }    /**
     * @return Lang
     */
    public function lang()
    {
        return $this->getObject('lang');
    }    /**
     * @return Product
     */
    public function product()
    {
        return $this->getObject('product');
    }    /**
     * @return ProductAttribute
     */
    public function productAttribute()
    {
        return $this->getObject('productAttribute');
    }    /**
     * @return ProductAttributeLang
     */
    public function productAttributeLang()
    {
        return $this->getObject('productAttributeLang');
    }    /**
     * @return ProductAttributeValue
     */
    public function productAttributeValue()
    {
        return $this->getObject('productAttributeValue');
    }    /**
     * @return ProductAttributeValueLang
     */
    public function productAttributeValueLang()
    {
        return $this->getObject('productAttributeValueLang');
    }    /**
     * @return ProductCard
     */
    public function productCard()
    {
        return $this->getObject('productCard');
    }    /**
     * @return ProductCardHasProduct
     */
    public function productCardHasProduct()
    {
        return $this->getObject('productCardHasProduct');
    }    /**
     * @return ProductCardLang
     */
    public function productCardLang()
    {
        return $this->getObject('productCardLang');
    }    /**
     * @return ProductHasProductAttribute
     */
    public function productHasProductAttribute()
    {
        return $this->getObject('productHasProductAttribute');
    }    /**
     * @return ProductLang
     */
    public function productLang()
    {
        return $this->getObject('productLang');
    }    /**
     * @return Shop
     */
    public function shop()
    {
        return $this->getObject('shop');
    }    /**
     * @return ShopConfiguration
     */
    public function shopConfiguration()
    {
        return $this->getObject('shopConfiguration');
    }    /**
     * @return ShopHasCurrency
     */
    public function shopHasCurrency()
    {
        return $this->getObject('shopHasCurrency');
    }    /**
     * @return ShopHasProductCard
     */
    public function shopHasProductCard()
    {
        return $this->getObject('shopHasProductCard');
    }    /**
     * @return ShopHasLang
     */
    public function shopHasLang()
    {
        return $this->getObject('shopHasLang');
    }    /**
     * @return ShopHasProduct
     */
    public function shopHasProduct()
    {
        return $this->getObject('shopHasProduct');
    }    /**
     * @return ShopHasProductLang
     */
    public function shopHasProductLang()
    {
        return $this->getObject('shopHasProductLang');
    }    /**
     * @return ShopHasStore
     */
    public function shopHasStore()
    {
        return $this->getObject('shopHasStore');
    }    /**
     * @return Store
     */
    public function store()
    {
        return $this->getObject('store');
    }    /**
     * @return StoreHasProduct
     */
    public function storeHasProduct()
    {
        return $this->getObject('storeHasProduct');
    }    /**
     * @return Timezone
     */
    public function timezone()
    {
        return $this->getObject('timezone');
    }
}